### ISSUE TITLE
Scoutfish

### ISSUE THREAD

**Issue by mcostalba** [moroshko/chessboard#1]
Integrate with https://github.com/mcostalba/scoutfish

Well, it is not an issue of course :-) I need a web UI for my project above and I was wondering if this code maybe suitable. I see is not maintained since a long time. Can you please tell me if it is complete/working or still WIP?

**Comment by moroshko** [comment]
I remember it was working pretty well a couple of years ago, but I have no plans to continue developing it further. You are more than welcome to fork it and extend it, if some functionality is missing.
